---
- name: Playbook to install Java & Tomcat on Multiple AWS-EC2 Instances
  hosts: all
  become: true
  gather_facts: false
  vars:
    tomcat9_url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.100/bin/apache-tomcat-9.0.100.tar.gz
  tasks:
    - name: Install Java-21 on Amazon Linux
      yum:
        name: java-21-amazon-corretto.x86_64
        state: present

    - name: Download Tomcat
      get_url:
        url: "{{tomcat9_url}}"
        dest: /opt

    - name: Extract Tomcat
      unarchive:
        src: /opt/apache-tomcat-9.0.100.tar.gz
        dest: /opt
        remote_src: yes

    - name: Provide Execute Permission to startup.sh
      file:
        path: /opt/apache-tomcat-9.0.100/bin/startup.sh
        mode: 0777

    - name: Start Tomcat Service
      shell: nohup ./startup.sh
      args:
        chdir: /opt/apache-tomcat-9.0.100/bin


